services:
  oracle:
    image: gvenzl/oracle-xe:21
    container_name: oracle-XE-21
    restart: always
    environment:
      ORACLE_ALLOW_REMOTE: "true"
      ORACLE_PASSWORD: 789789
      APP_USER: luciano
      APP_USER_PASSWORD: 789789
    ports:
      - "1521:1521"
    volumes:
      - database:/var/lib/oracle
networks:
  oracle:
    driver: bridge
volumes:
  database:
