services:
  postgres:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=290686Lu*
      - MSSQL_PID=developer
      - ACCEPT_EULA=Y 
    volumes:
       - database:/var/lib/sqlserver
    ports:
      - "1433:1433"
    networks:
      - sqlserver
    restart: always

networks:
  sqlserver:
    driver: bridge
volumes:
  database:

