services:
  db:
    image: mariadb:11.1.2
    container_name: mariadb
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 789789
      MYSQL_USER: luciano
      MYSQL_PASSWORD: 290686Lu*
    volumes:
      - database:/var/lib/mariadb
    ports:
      - "3309:3306"
networks:
  mariadb:
    driver: bridge
volumes:
  database:


