services:
  db:
    image: mariadb:11.1.2
    network_mode: bridge
    container_name: mariadb
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 290686Lu*
      MYSQL_USER: luciano
      MYSQL_PASSWORD: 789789
    volumes:
      - database:/var/lib/mariadb
    ports:
      - "3309:3306"
volumes:
  database:


