services:
  db:
    image: mysql:8.0
    network_mode: bridge
    container_name: mysql-8
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 290686Lu*
      MYSQL_ROOT_USER: luciano
      MYSQL_PASSWORD: 290686Lu*
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
networks:
  mysql:
    driver: bridge
volumes:
  database:
