services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 789789
      PGDATA: /data/postgres
    volumes:
       - database:/var/lib/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always
networks:
  postgres:
    driver: bridge
volumes:
  database:
